### ISSUE TITLE
mention copying hidden files

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/unix-cli#20]
Comes up later when trying to unzip repos.

Via @gaand

**Comment by RealWeeks** [comment]
@gaand  cp -r? Noted, not added. Will emphasize during delivery.

**Comment by gaand** [comment]
``` sh
cp -a <source> <destination>
```

On a real operating system, you can type

``` sh
cp --archive  <source> <destination>
```

**Comment by jrhorn424** [comment]
> On a real operating system, you can type

lol

**Comment by jrhorn424** [comment]
@MicFin Unassigned for now. Let's get this done next time.
